- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  connection: ssh
  tasks:
    - name: Update apt
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker Service
      service:
        name: docker
        state: started

    - name: Deploy Docker Container
      command: docker run -itd -p 8085:8081 vishalhatkare358/project:1
